### ISSUE TITLE
Path Based instead of Host Based

### ISSUE THREAD

**Issue by capitalist** [slogsdon/elixir-reverse-proxy#1]
Do you think it would be possible to wire this up inside a Phoenix app such that example.com/some-path really goes to the upstream instead of some-host.example.com?

**Comment by slogsdon** [comment]
Most likely, but I'd first want to see how this acts within another Plug-based application, like an application built with Phoenix.

I'll try to take a look soon to see what would be required.

**Comment by capitalist** [comment]
Roger that. I'll let you know when I get a chance to try this if I get it working.

I want to do it so a Phoenix app can control the domain example.com but example.com/some-path can be reverse proxied to an upstream that doesn't support CORS or JSONP

**Comment by slogsdon** [comment]
@capitalist, this is definitely possible. Here's a super simple test with a `Plug.Router` (using the [`forward/2` macro](https://github.com/elixir-lang/plug/blob/master/lib/plug/router.ex#L271-L322)) and no configuration for the reverse proxy:

<img width="1915" alt="screen shot 2015-08-20 at 9 38 09 pm" src="https://cloud.githubusercontent.com/assets/647624/9399541/11b4bd6a-4784-11e5-8ff8-11a45b4f644c.png">

The `400 Bad Request` response is coming from `ReverseProxy` as it's the default match for the plug. Also, I did a quick search, and it looks like Phoenix has a [similar macro](https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/router.ex#L596-L628).

There are a few things that need to be improved before this could be useful:
- **Allow for a default match.** Currently, some sort of compatible `:host` string is required when configuring the upstreams. This is used at compile time to build the calls to `Plug.Router.match/2`.
- **Unit/Integration tests.** Currently, there aren't any. These should also flush out any other improvements/changes necessary.

**Comment by capitalist** [comment]
This is very awesome. Thanks for that! I'm going to use this to build a web app that is Phoenix up front, with several others in the back. Makes it easy to use each tool at what it's best at.

**Comment by elbow-jason** [comment]
I would consider adding this to the README or docs. It is very helpful.

**Comment by slogsdon** [comment]
Will do, @elbow-jason! This was an unintended use case, but it's definitely a useful one.

**Comment by slogsdon** [comment]
I began an [embedding section](https://github.com/slogsdon/elixir-reverse-proxy/blob/master/README.md#embedding) in the README and will enhance it as the feature is improved.
