### ISSUE TITLE
Should 'upstreams' take URI's?

### ISSUE THREAD

**Issue by davidw** [slogsdon/elixir-reverse-proxy#14]
That's what Apache does: https://httpd.apache.org/docs/2.4/mod/mod_proxy.html

This would make things more configurable in terms of pointing to an SSL site from an non-SSL request, and things like that.

**Comment by slogsdon** [comment]
This would probably be a good idea and should be a trivial change to [this line](https://github.com/slogsdon/elixir-reverse-proxy/blob/master/lib/reverse_proxy/runner.ex#L43) to account for URIs

**Comment by davidw** [comment]
Yeah, that's what I did; I'll send in the PR.

**Comment by slogsdon** [comment]
Closed via #15
